config/routes.rb
EshTestApp::Application.routes.draw do
  
  root to: 'main#index'

  devise_for :users

  get '/location', to: 'main#location'

  get '/contact', to: 'main#contact'

  get '/instructors', to: 'main#instructors'

  get '/workshops', to: 'main#workshops'

  get '/disciplines', to: 'main#disciplines'

  get '/upcoming_classes', to: 'main#upcoming_classes'

  get '/private_lessons', to: 'main#private_lessons'

  get '/student', to: 'users#student_index'

  get '/instructor', to: 'users#instructor_index'

  get '/admin', to: 'admin#admin_index'

  get '/recent_registrations', to: 'admin#recent_registrations'

  resources :main

  resources :course_registrations

  resources :disciplines

  resources :courses

  resources :users

  resources :charges

  resources :seven_week_sessions

  

end

app/views/admin/admin_index.html.erb
<ul>
	<li><%= link_to "All Esh Community Members", users_path %></li>
	<li><%= link_to "Add New Instructor or Student", new_user_path %></li>
	<li><%= link_to "Update Disciplines List and Descriptions", disciplines_path %></li>
	<li><%= link_to "Add a new Discipline", new_discipline_path %></li>
	<li><%= link_to "Add New Workshops", new_course_path %></li>
	<li><%= link_to "Add New Seven-Week Sessions", new_seven_week_session_path %></li>
	<li><%= link_to "Recent Course Registrations", recent_registrations_path %>
	</li>
</ul>

app/views/admin/recent_registrations.html.erb
<h2>Recent Course Registrations</h2>

<ol>

<% @registrations.each do |registration| %>

	<% if registration.role == "student" %>

	  <li>Registration # <%= registration.id %>:</li>
    <ul>
		  <li><%= link_to registration.user.name, user_path(registration.user) %></li>

		  <li>Course: <%= link_to registration.registerable.name, registerable_url([registeration.registerable_type.to_sym, registration]) %> 
		    <%= render 'shared/course_time', :course => registration.registerable  %></li>
		  <li><% if registration.paid %> Paid <% else %> Not yet paid <% end %></li>
		  <p><%= registration.created_at.strftime("%m/%d/%Y, %-l:%M %P") %> </p>
    </ul>
  <% else %>

    <li><%= link_to registration.user.name, user_path(registration.user) %> was assigned to teach: 
    <%= link_to registration.registerable.name, registerable_url([registeration.registerable_type.to_sym, registration]) %> 
	  <%= render 'shared/course_time', :course => registration.registerable  %> </li>
	  <p><%= registration.created_at.strftime("%m/%d/%Y, %-l:%M %P ") %> </p>

	<% end %>

	  <% if current_user.admin %>
      <span><%= link_to 'Show', registration %></span> | 
      <span><%= link_to 'Edit', edit_course_registration_path(registration) %></span> | 
      <span><%= link_to 'Delete', registration, method: :delete, data: { confirm: 'Are you sure?' } %></span>
    <% end %>
  

<% end %>

</ol>