config/routes.rb
EshTestApp::Application.routes.draw do
  
  root to: 'main#index'

  devise_for :users

  get '/location', to: 'main#location'

  get '/contact', to: 'main#contact'

  get '/instructors', to: 'main#instructors'

  get '/workshops', to: 'main#workshops'

  get '/disciplines', to: 'main#disciplines'

  get '/upcoming_classes', to: 'main#upcoming_classes'

  get '/private_lessons', to: 'main#private_lessons'

  get '/student', to: 'users#student_index'

  get '/instructor', to: 'users#instructor_index'

  get '/admin', to: 'admin#admin_index'

  get '/recent_registrations', to: 'admin#recent_registrations'

  resources :main

  resources :course_registrations

  resources :disciplines

  resources :courses

  resources :users

  resources :charges

  resources :seven_week_sessions

  

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :course_registrations
  has_many :courses, :through => :course_registrations, :source => :registerable, :source_type => "course_registrations.registerable_type = 'Course'"
  has_many :seven_week_sessions, :through => :course_registrations, :source => :registerable, :source_type => "course_registrations.registerable_type = 'SevenWeekSession'"


  def unpaid_balance
  	unpaid_course_registrations = CourseRegistration.where(user_id: self.id, paid: nil, role: "student").where('price is not null')
  	balance = 0
  	unpaid_course_registrations.each do |course_registration|
  		  balance += course_registration.price
  	end
  	return balance
  end

  def courses_teaching
    CourseRegistration.where(user_id: self.id, role: "instructor").current
  end

  def courses_taking
    CourseRegistration.where(user_id: self.id, role: "student").current
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user! 

  # GET /users
  # GET /users.json
  def index
    redirect_to :new_user_session_path unless current_user && current_user.admin
    @students = User.where(instructor: nil)
    @instructors = User.where(instructor: true)
  end

  def student_index
    @courses_teaching = CourseRegistration.where(user_id: current_user.id, role: "instructor").current
    @courses_taking = CourseRegistration.where(user_id: current_user.id, role: "student").current
  end

  def instructor_index
    @my_courses = CourseRegistration.where(user_id: current_user.id, role: "instructor").current.map do |reg|
      reg.registerable
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @courses_teaching = CourseRegistration.where(user_id: @user.id, role: "instructor").current
    @courses_taking = CourseRegistration.where(user_id: @user.id, role: "student").current
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :courses, :course_registrations, :bio, :instructor, :admin, :injuries, :photo, :password, :emergency_contact_name, :emergency_contact_number, :email, :phone_number, :address)
    end
end

app/helpers/users_helper.rb
module UsersHelper
  def show_classes
  	self.course_registrations.where(role: "teacher").pluck(:course).each do |course|
      "#{ link_to course.name, course }".html_safe
    end
  end
end

app/views/users/_form.html.erb
<% if current_user %>

    <% if @user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

        <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <%= form_for(@user) do |f| %>

        <div class="field">
          <%= f.label :email %><br>
          <%= f.text_field :email %>
        </div>

        <div class="field">
          <%= f.label :name %><br>
          <%= f.text_field :name %>
        </div>

        <div class="field">
          <%= f.label :bio %><br>
          <%= f.text_area :bio %>
        </div>

        <div class="field">
          <%= f.label :injuries %><br>
          <%= f.text_field :injuries %>
        </div>

        <div class="field">
          <%= f.label :emergency_contact_name %><br>
          <%= f.text_field :emergency_contact_name %>
        </div>

        <div class="field">
          <%= f.label :emergency_contact_number %><br>
          <%= f.text_field :emergency_contact_number %>
        </div>

        <div class="field">
          <%= f.label :phone_number %><br>
          <%= f.text_field :phone_number %>
        </div>
        <div class="field">
          <%= f.label :address %><br>
          <%= f.text_area :address %>
        </div>

      <% if current_user.try(:admin?) %>
      
        <h5>Show this person's bio on the Esh Instructors Page?</h5>
        <div class="field">
          <%= f.label :instructor? %><br>
          <%= f.check_box :instructor %>
        </div>
        
        <h5>Make this person an Esh Website Administrator?</h5>
        <div class="field">
          <%= f.label :admin? %><br>
          <%= f.check_box :admin %>
        </div>

      <% end %>

        <div class="actions">
          <%= f.submit %>
        </div>

    <% end %>

<% end %>

app/views/users/edit.html.erb
<h1>Edit user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', student_path %>

app/views/users/index.html.erb
<% if current_user.admin %>

  <%= link_to 'Enter a New Student or Instructor', new_user_path %>

  <h1>All Esh Community Members</h1>

  <h2>Students</h2>
  <% @students.each do |user| %>
    <%= render 'shared/show_user', :user => user %>
    <div class="container">      
      <span><%= link_to 'Show', user %></span> | 
      <span><%= link_to 'Edit', edit_user_path(user) %></span> | 
      <span><%= link_to 'Delete', user, method: :delete, data: { confirm: 'Are you sure?' } %></span>
    </div>
  <% end %>

  <h2>Instructors</h2>
  <% @instructors.each do |user| %>
    <%= render 'shared/show_user', :user => user %>
    <div class="container">      
      <span><%= link_to 'Show', user %></span> | 
      <span><%= link_to 'Edit', edit_user_path(user) %></span> | 
      <span><%= link_to 'Delete', user, method: :delete, data: { confirm: 'Are you sure?' } %></span>
    </div>
  <% end %>

<% else %>
  <%= link_to 'My profile', student_path %>
<% end %>

app/views/users/instructor_index.html.erb
<% if current_user.instructor %>
	<h3>Classes I am teaching</h3>
	<ul>
	<% @my_courses.each do |registerable| %>
	  <li><%= link_to registerable.name, registerable %><%= render 'shared/course_time', :registerable => registerable  %></li>

      <ol>
		  <% registerable.course_registrations.each do |registration| %>
			    <% if registration.role == "student" %> 
				    <li><%= link_to registration.user.name, user_path(registration.user) %> 
				    Comments: <%= registration.comments %></li>
				      <% unless registration.paid %>
		            Tuition owed: $<%= registration.price %>.00
				      <% end %>
			    <% end %>
		  <% end %>
      </ol>
      <%= registerable.spots_left %> spots left in this class.
  <% end %>
  </ul>
	

<% end %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<% if @user.instructor %>
  <h2><%= @user.name %></h2>
  
  <%= render 'shared/show_user', :user => @user %>
    <h4><%= @user.name %> is teaching these classes:</h4>
    <ul>
      <% @user.courses_teaching.each do |reg| %>
        <li><%= link_to reg.registerable.short_description, reg.registerable %> </li>
      <% end %>
    </ul>
    
<% elsif current_user.try(:instructor?) || current_user == @user %>

  <h2><%= @user.name %></h2>
  
  <%= render 'shared/show_user', :user => @user %>
    <h4><%= @user.name %> is taking these classes:</h4>
    <ul>
      <% @courses_taking.each do |reg| %>
        <li><%= link_to reg.registerable.short_description, reg.registerable %></li>
      <% end %>
    </ul>


<% end %>

app/views/users/student_index.html.erb
<% if current_user %>
	<% if current_user.instructor %>
	  <h4>Your bio and photo will be visible to the public on the instructors page.</h4>
	  <h5>The rest of your personal information is only viewable by other Esh staff</h5>
	<% else %>
	  <h4>Your student profile</h4>
	  <h5>This information will be shared with your instructors.</h5>
	<% end %>

	<%= render 'shared/show_user', :user => current_user %>

	<p><%= link_to "update my profile", edit_user_path(current_user) %></p>
	<p><%= link_to "see my current course registrations", course_registrations_path %></p>

<% end %>