config/routes.rb
EshTestApp::Application.routes.draw do
  
  root to: 'main#index'

  devise_for :users

  get '/location', to: 'main#location'

  get '/contact', to: 'main#contact'

  get '/instructors', to: 'main#instructors'

  get '/workshops', to: 'main#workshops'

  get '/disciplines', to: 'main#disciplines'

  get '/upcoming_classes', to: 'main#upcoming_classes'

  get '/private_lessons', to: 'main#private_lessons'

  get '/student', to: 'users#student_index'

  get '/instructor', to: 'users#instructor_index'

  get '/admin', to: 'admin#admin_index'

  get '/recent_registrations', to: 'admin#recent_registrations'

  resources :main

  resources :course_registrations

  resources :disciplines

  resources :courses

  resources :users

  resources :charges

  resources :seven_week_sessions

  

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  # GET /courses
  # GET /courses.json

  # GET /courses/1
  # GET /courses/1.json
  def show
    @my_registration = CourseRegistration.where(user_id: current_user.id, registerable_id: @course.id, registerable_type: "Course").first
    @course_registration = CourseRegistration.new
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    
    @course = Course.new(course_params)
    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render action: 'show', status: :created, location: @course }
      else
        format.html { render action: 'new' }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])

      @instructors = @course.instructor_ids.map do |id|
        User.find(id)
      end

    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params["course"]["instructor_ids"].delete("")
      params["course"]["instructor_ids"].map! {|x| x.to_i }
      params.require(:course).permit(:name, :start_date, :start_time, :end_time, :user_ids, :seven_week_session_id, :discipline_id, :registration_ids, :number_of_sessions, :price, :drop_in_price, :level, :description, :discipline, :instructor_ids => [])
    end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_form.html.erb
<% if user_signed_in? && current_user.admin || current_user.instructor%>
  <%= form_for(@course) do |f| %>
    <% if @course.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h2>

        <ul>
        <% @course.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>

    <div class="field">
      <%= f.label :instructor_or_instructors %><br>
      <%= collection_check_boxes(:course, :instructor_ids, User.where(instructor: true), :id, :name) %>
    </div>

    <div class="field">
      <%= f.label :start_date %><br>
      <%= f.date_select :start_date %>
    </div>

    <div class="field">
      <%= f.label :start_time %><br>
      <%= f.time_select :start_time %>
    </div>

    <div class="field">
      <%= f.label :end_time %><br>
      <%= f.time_select :end_time %>
    </div>

    <div class="field">
      <%= f.label :max_class_size %><br>
      <%= f.number_field :max_class_size %>
    </div>

  <% if @course.seven_week_session %>
    <div class="field">
      <%= f.label :drop_in_price %><br>
      <%= f.number_field :drop_in_price %>
    </div>
  <% else %>
    <div class="field">
      <%= f.label :one_time_workshop_price %><br>
      <%= f.number_field :price %>
    </div>
  <% end %>

    <div class="field">
      <%= f.label :level %><br>
      <%= f.number_field :level %>
    </div>
    <div class="field">
      <%= f.label :description %><br>
      <%= f.text_area :description %>
    </div>
    <div class="field">
      <%= f.label :discipline %><br>
      <%= collection_select(:course, :discipline_id, Discipline.all, :id, :name) %>
    </div> 
    <br>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing course</h1>

<%= render 'form' %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', upcoming_classes_path %>

app/views/courses/new.html.erb
<h1>New Workshop</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_path %>

app/views/courses/show.html.erb
  <p id="notice"><%= notice %></p>

<% if @course.users.include? current_user %>
  
  <%= link_to "Can't make it?  Let us know.", edit_course_registration_path(@my_registration.id) %>

<% else %>
  
  <% if @course.future %>
   
      <%= form_for @course_registration, action: 'create' do |f| %>
     
        <h3><%= @course.name %></h3>
        <p><%= @course.description %></p>
      
        <% if @course.drop_in_price %>
          <p>Drop-in Price: $<%= @course.drop_in_price %>.00</p>
          <%= f.hidden_field :price, value: @course.drop_in_price %>
        <% else %>
          <p>Workshop price: $<%= @course.price %>.00</p>
          <%= f.hidden_field :price, value: @course.price %>
        <% end %>

        <%= render 'shared/course_time', :registerable => @course  %>

        <%= @course.spots_left %> spots left.

      <div class="field">
        <%= f.label :additional_information_for_your_instructors %><br>
        <%= f.text_area :comments %>
      </div>

        <%= f.hidden_field :registerable_id, value: @course.id %>
        <%= f.hidden_field :registerable_type, value: "Course" %>
        <%= f.hidden_field :user_id, value: current_user.id %>

        <% unless @course.full %>
          <%= f.submit "Register for #{@course.name}" %>
        <% else %>
          <strong>This class is full.  Please <%= mail_to "scheduling@eshaerialarts.com", "contact us"%> to get on the waiting list. </strong>
        <% end %>

      <% end %>

  <% end %>
<% end %>



<h3><%= @course.short_description %></h3>

  <p>
    <strong>Instructor(s):</strong>
    <% @instructors.each do |instructor| %>
      <%= link_to instructor.name, user_path(instructor) %>
    <% end %>
  </p>
  
  <% if @course.seven_week_session_id %>
    <p>
      <strong>Part of a seven-week session:</strong>
      <%= link_to @course.seven_week_session.name, @course.seven_week_session %>
    </p>
  <% end %>

  <p>
    <strong>Spots left:</strong>
    <%= @course.spots_left %>
  </p>

  <p>
    
    <% if @course.drop_in_price%>
    <strong>Drop-In Price:</strong>
      $<%= @course.drop_in_price %>.00
    <% else %>
    <strong>Workshop Price:</strong>
      $<%= @course.price %>.00
    <% end %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= @course.description %>
  </p>

<% if current_user.try(:instructor?) || current_user.try(:admin?) %>

    <strong>All Students:</strong>
    <ol>
    <% @course.users.each do |user| %>
      <% unless @course.instructor_ids.include? user.id %>
        <li><%= link_to user.name, user_path(user) %></li>
      <% end %>
    <% end %>
    </ol>

  <%= link_to 'Edit', edit_course_path(@course) %> | <%= link_to 'Delete', @course, method: :delete, data: { confirm: 'Are you sure?' } %>

<% end %>