config/routes.rb
EshTestApp::Application.routes.draw do
  
  root to: 'main#index'

  devise_for :users

  get '/location', to: 'main#location'

  get '/contact', to: 'main#contact'

  get '/instructors', to: 'main#instructors'

  get '/workshops', to: 'main#workshops'

  get '/disciplines', to: 'main#disciplines'

  get '/upcoming_classes', to: 'main#upcoming_classes'

  get '/private_lessons', to: 'main#private_lessons'

  get '/student', to: 'users#student_index'

  get '/instructor', to: 'users#instructor_index'

  get '/admin', to: 'admin#admin_index'

  get '/recent_registrations', to: 'admin#recent_registrations'

  resources :main

  resources :course_registrations

  resources :disciplines

  resources :courses

  resources :users

  resources :charges

  resources :seven_week_sessions

  

end

app/models/course_registration.rb
class CourseRegistration < ActiveRecord::Base
  belongs_to :user
  belongs_to :registerable, polymorphic: true, counter_cache: true
  scope :current, -> { where("'course.start_date' > ?", Date.today)}
  before_validation :create_sub_registrations
  validates :role, inclusion: { in: %w(student instructor)}

  def self.check_out(user)
    unpaid_reg = user.course_registrations.where(paid: nil)
    unpaid_reg.each do |reg|
      reg.paid = true 
      reg.save
    end
  end

  def create_sub_registrations
    if self.registerable_type == "SevenWeekSession"
      self.registerable.courses.each do |course|
        CourseRegistration.create(user_id: self.user_id, role: self.role, paid: self.paid, sub: true, registerable_id: course.id, registerable_type: "Course", price: nil, comments: self.comments)
      end
    end
  end

  def name
    registerable.name
  end

  def is_full_registration
    self.price
  end
  
end

app/controllers/course_registrations_controller.rb
class CourseRegistrationsController < ApplicationController
  before_action :set_course_registration, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user! #unless user_signed_in? 
  
  # GET /course_registrations
  # GET /course_registrations.json
  def index
    @course_registrations = CourseRegistration.where(user_id: current_user.id).order("start_date ASC").current
  end

  # GET /course_registrations/1
  # GET /course_registrations/1.json
  def show
    @course_registrations = CourseRegistration.where(user_id: current_user.id).current
  end

  # GET /course_registrations/new
  def new
    @sessions = SevenWeekSession.future.where_user_not_registered(current_user)
    @courses = Course.future.where_user_not_registered(current_user)
    @course_registration = CourseRegistration.new
  end

  # GET /course_registrations/1/edit
  def edit
    if @course_registration.registerable_type == "Course"
      @equivalent_courses = Course.future.equivalent(@course_registration.registerable.one_time_price).where_user_not_registered(current_user)
    elsif @course_registration.registerable_type == "SevenWeekSession"
      @equivalent_courses = SevenWeekSession.future.equivalent(@course_registration.registerable.full_price)
    end
  end

  # POST /course_registrations
  # POST /course_registrations.json
  def create

    @course_registration = CourseRegistration.new(course_registration_params)
    respond_to do |format|
      if @course_registration.save
        format.html { render action: 'show', notice: "Registration successful! Want to register for another class?" }
        format.json { render action: 'show', status: :created, location: @course_registration }
      else
        format.html { render action: 'new' }
        format.json { render json: @course_registration.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /course_registrations/1
  # PATCH/PUT /course_registrations/1.json
  def update
    respond_to do |format|
      if @course_registration.update(course_registration_params)
        format.html { redirect_to @course_registration, notice: 'Registration successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @course_registration.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /course_registrations/1
  # DELETE /course_registrations/1.json
  def destroy
    @course_registration.destroy
    respond_to do |format|
      format.html { redirect_to course_registrations_path}
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course_registration
      @course_registration = CourseRegistration.find(params[:id])
    end

    def registerable_id
      params[(params[:registerable] + "_id").to_sym]
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_registration_params
      params.require(:course_registration).permit(:user_id, :registerable_id, :course_id, :seven_week_session_id, :sub, :registerable_type, :price, :paid, :comments)
    end
    
end

app/helpers/course_registrations_helper.rb
module CourseRegistrationsHelper

end

app/views/course_registrations/edit.html.erb
<h2>Edit Course Registration</h2>

<p class="lead">
You are registered for <%= @course_registration.registerable.short_description %> </p>

  <%= form_for @course_registration, action: 'create', role: 'form' do |f| %>
        
    <strong>
    Anything we should know?  Send a message to the Esh staff here.
    </strong>
    
    <div class="form-group">
      <%= f.text_area :comments, value: ""%>
    </div>
      
    <p class="lead"> 
    Can't make it? Come to make up week or drop in to another class.
    </p>

    <div class="form-group">
      <%= f.label :Substitute_Class %><br>
      <%= f.collection_select :registerable_id, @equivalent_courses, :id, :short_description %>
    </div>
      <%= f.hidden_field :user_id, value: current_user.id %>
      <%= f.hidden_field :role, value: "student" %>

    <div class="form-group">
      <%= f.submit "Update your registration" %>
    </div>
    
<% end %>

<% if @course_registration.paid == nil && !current_user.admin %>
  <strong><%= link_to "Pay Now", new_charge_path %></strong> | 
  <strong><%= link_to 'Delete this registration ', @course_registration, method: :delete, data: { confirm: 'Are you sure?' } %></strong> | 
<% end %>

<% if current_user.try(:admin?) %>
  <strong><%= link_to 'Delete this registration ', @course_registration, method: :delete, data: { confirm: 'Are you sure?' } %></strong> | 
<% end %>

<strong><%= link_to 'Register for more classes', new_course_registration_path %></strong>

app/views/course_registrations/index.html.erb
<% if current_user.courses_teaching.size > 0 %>
  <strong>You are teaching:</strong>
  <ul>
    <% current_user.courses_teaching.each do |course_registration| %>
    
      <% if course_registration.registerable_type == "SevenWeekSession" %>
        <li> 
          <%= link_to course_registration.registerable.short_description, course_registration.registerable %> 
          <%= course_registration.registerable.spots_left %> out of <%= course_registration.registerable.max_class_size %> spots left.
        </li>
        <ul>
        <% course_registration.registerable.courses.each do |course| %>
          <li><%= link_to course.short_description, course %>
            <%= course.spots_left %> out of <%= course.max_class_size %> spots left.
          </li>
        <% end %>
        </ul>
      <% elsif course_registration.registerable.number_of_sessions == 1 %>
        <li> 
          <%= link_to course_registration.registerable.short_description, course_registration.registerable %> 
          <%= course_registration.registerable.spots_left %> out of <%= course_registration.registerable.max_class_size %> spots left.
        </li>
      <% end %>
      
    <% end %>
  </ul>

<% end %>

<% if current_user.courses_taking.size > 0 %>
  <strong>You are registered as a student for:</strong><br>

  <ul>
  <% current_user.courses_taking.each do |course_registration| %>
    
      <li><%= link_to course_registration.registerable.short_description, course_registration %></li>
      <% if !course_registration.paid && course_registration.is_full_registration  %>
      <strong>reserved pending payment of $<%= course_registration.price%>.00</strong>
      <% end %>
  <% end %>  
  
  </ul> 
<% end %>
 

<br>
<% if current_user.unpaid_balance > 0 %>
  <strong>Your unpaid balance:</strong>
  $<%= current_user.unpaid_balance %>.00
  <h3><%= link_to "Pay Now", new_charge_path %></h3>
<% end %>

<p><%= link_to "Register for classes", new_course_registration_path %></p>

app/views/course_registrations/new.html.erb
<h1>Register for Upcoming Courses</h1>

<%= link_to "See my current registrations", course_registrations_path %>

<h2>Upcoming Seven-Week Sessions</h2>


  <% @sessions.each do |seven_week_session| %>

      <% if @course_registration.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@course_registration.errors.count, "error") %> prohibited this course_registration from being saved:</h2>

          <ul>
          <% @course_registration.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
   
        <%= form_for @course_registration, action: 'create' do |f| %>
       
          <h3><%= seven_week_session.name %></h3>
          <p><%= seven_week_session.description %></p>

          <p>Full Price for Seven-Week Session: $<%= seven_week_session.full_price %>.00</p>
          <%= f.hidden_field :price, value: seven_week_session.full_price %>

          <%= render 'shared/course_time', :registerable => seven_week_session  %>

          <%= seven_week_session.spots_left %> spots left.

          <div class="field">
            <%= f.label :additional_information_for_your_instructors %><br>
            <%= f.text_area :comments %>
          </div>

          <%= f.hidden_field :registerable_type, value: "SevenWeekSession" %>
          <%= f.hidden_field :registerable_id, value: seven_week_session.id %>
          <%= f.hidden_field :user_id, value: current_user.id %>

          <% unless seven_week_session.full %>
            <%= f.submit "Register for #{seven_week_session.name}" %>
          <% else %>
            <strong>This class is full.  Please <%= mail_to "scheduling@eshaerialarts.com", "contact us"%> to get on the waiting list. </strong>
          <% end %>

      <% end %>

  <% end %>


<h2>Upcoming Workshops and Drop-in Classes</h2>

<% @courses.each do |course| %>
    <% if @course_registration.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@course_registration.errors.count, "error") %> prohibited this course_registration from being saved:</h2>

        <ul>
        <% @course_registration.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

        <%= form_for @course_registration, action: 'create' do |f| %>
       
          <h3><%= course.name %></h3>
          <p><%= course.description %></p>

          <% if course.try(:drop_in_price?) %>
            <p> Drop-in Price: $<%= course.drop_in_price%>.00 </p>
            <%= f.hidden_field :price, value: course.drop_in_price %>
          <% else course.price %>
            <p>Price $<%= course.price%>.00</p>
            <%= f.hidden_field :price, value: course.price %>
          <% end %>

          <%= render 'shared/course_time', :registerable => course  %>

          <%= course.spots_left %> spots left.

          <div class="field">
            <%= f.label :additional_information_for_your_instructors %><br>
            <%= f.text_area :comments %>
          </div>

          <%= f.hidden_field :registerable_id, value: course.id %>
          <%= f.hidden_field :registerable_type, value: "Course" %>
          <%= f.hidden_field :user_id, value: current_user.id %>

          <% unless course.full %>
            <%= f.submit "Register for #{course.name}" %>
          <% else %>
            <strong>This class is full.  Please <%= mail_to "scheduling@eshaerialarts.com", "contact us"%> to get on the waiting list. </strong>
          <% end %>

        <% end %>

  <% end %>


<h3><%= link_to "Pay Now", new_charge_path %></h3>


<h3><%= link_to 'See my current registrations', course_registrations_path %></h3>

app/views/course_registrations/show.html.erb
<p id="notice"><%= notice %></p>

<h2>New class registration created for: </h2>
<p><%= current_user.name %> <%= @course_registration.user.email %></p>

<p>
  <strong>Class:</strong>
  <% if @course_registration.registerable_type == "SevenWeekSession" %>
    <%= link_to @course_registration.registerable.name, seven_week_session_path(@course_registration.registerable) %> starting on 
    <%= @course_registration.registerable.start_date.strftime("%A, %B %-d, %Y") %>
  <% elsif @course_registration.registerable_type == "Course" %>
    <%= link_to @course_registration.registerable.name, course_path(@course_registration.registerable) %> on 
    <%= @course_registration.registerable.start_date.strftime("%A, %B %-d, %Y") %>
  <% end %>
</p>

<p>
<% unless @course_registration.sub  || @course_registration.paid %>
  <strong>Tuition for this course:</strong>
  $<%= @course_registration.price %>.00
<% end %>
</p>
 
<strong><%= link_to 'Edit this registration', edit_course_registration_path(@course_registration) %> </strong>
<strong><%= link_to "See all my registrations", course_registrations_path %></strong>

<% if current_user.unpaid_balance > 0 %>
  <h3><%= link_to "Pay Now", new_charge_path %></h3>
<% end %>